import Header from '@/app/components/Header';
import './globals.scss';
import 'react-toastify/dist/ReactToastify.min.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/app/components/Footer';
import Providers from '@/app/components/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en">
			<body className={`${inter.className}`}>
				<Providers>
					<Header />
					{children}
					<Footer />
				</Providers>
			</body>
		</html>
	);
};

export default RootLayout;
